name: dartz_plus_generator_example
description: Example usage of dartz_plus_generator
publish_to: none

environment:
  sdk: ^3.10.4

dependencies:
  dartz_plus:
    path: ../../dartz_plus

dev_dependencies:
  build_runner: ^2.10.4
  dartz_plus_generator:
    path: ../
