name: dartz_plus_generator_example
description: Example usage of dartz_plus_generator
publish_to: none

resolution: workspace

environment:
  sdk: ">=3.10.4 <4.0.0"

dependencies:
  dartz_plus:

dev_dependencies:
  build_runner: ^2.10.4
  dartz_plus_generator:
