name: dartz_plus_example
description: Example Flutter app demonstrating dartz_plus usage
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  dartz_plus:
    path: ../packages/dartz_plus
  equatable: ^2.0.7
  dio: ^5.9.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  freezed: ^3.2.4
  json_serializable: ^6.7.1
  dartz_plus_generator:
    path: ../packages/dartz_plus_generator

flutter:
  uses-material-design: true
