name: dartz_plus_generator
description: Code generator for dartz_plus AutoMapper.
version: 0.3.0
homepage: https://github.com/muhammadkamel/dartz_plus
repository: https://github.com/muhammadkamel/dartz_plus
license: MIT

resolution: workspace

environment:
  sdk: ">=3.10.4 <4.0.0"

dependencies:
  analyzer: ^9.0.0
  build: ^4.0.3
  collection: ^1.19.1
  dartz_plus: ^0.3.0
  source_gen: ^4.1.1

dev_dependencies:
  build_runner: ^2.10.4
  lints: ^6.0.0
  source_gen_test: ^1.3.3
  test: ^1.26.3
